### ISSUE TITLE
Unable to function properly

### ISSUE THREAD

**Issue by Leoparking** [Kihsomray/CyberWorldReset#3]
`[22:33:57 INFO]: The_Leopard_King issued server command: /cwr confirm
[22:33:57 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cwr'
 in plugin CyberWorldReset v0.6.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[pap
er-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:15
5) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServ
er.java:991) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(Bukk
itCommandWrapper.java:64) ~[paper-1.20.2.jar:git-Paper-318]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java
:265) ~[paper-1.20.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?
:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?
:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChat
Command(ServerGamePacketListenerImpl.java:2208) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$hand
leChatCommand$19(ServerGamePacketListenerImpl.java:2168) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(Blo
ckableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source
) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.ja
r:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEvent
Loop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(Reent
rantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1
324) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[pa
per-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventL
oop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer
.java:1301) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:12
94) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEv
entLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServe
r.java:1272) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1
160) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.ja
va:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.StringIndexOutOfBoundsException: Range [0, -18) out of boun
ds for length 11
        at jdk.internal.util.Preconditions$1.apply(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions$1.apply(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions$4.apply(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions$4.apply(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown S
ource) ~[?:?]
        at jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source) ~[?:
?]
        at java.lang.String.checkBoundsBeginEnd(Unknown Source) ~[?:?]
        at java.lang.String.substring(Unknown Source) ~[?:?]
        at net.zerotoil.cyberworldreset.utilities.ZipUtils.getLastModified(ZipUt
ils.java:31) ~[CyberWorldReset-0.6.2.jar:?]
        at net.zerotoil.cyberworldreset.objects.WorldObject.regenWorld(WorldObje
ct.java:124) ~[CyberWorldReset-0.6.2.jar:?]
        at net.zerotoil.cyberworldreset.commands.CWRCommand.argsLen1(CWRCommand.
java:148) ~[CyberWorldReset-0.6.2.jar:?]
        at net.zerotoil.cyberworldreset.commands.CWRCommand.onCommand(CWRCommand
.java:52) ~[CyberWorldReset-0.6.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pap
er-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more`

This my config.yml
`config:
  
  # should admins be forced to confirm before resetting a world?
  confirmation:
    enabled: true
    seconds: 15
  
  # should the world save before resetting?
  save-world-before-reset: false
  
  # STANDARD - only loads in spawn chunks.
  # Not recommended, drops TPS and lags players.
  
  # ULTRA-SAFE - loads in chunks, over a long period of time.
  # Recommended for low-end CPUS or large amounts of players.
  
  # SAFE - loads in chunks, over a longer period of time.
  # Recommended for low/mid-end CPUS or large amounts of players.
  
  # NORMAL - loads in chunks, over an 'average' period of time.
  # Recommended for mid-end CPUS or medium amounts of players.
  
  # FAST - loads in chunks, over a faster period of time.
  # Recommended for high-end CPUS or small amounts of players.
  
  # ULTRA-FAST - force loads chunks when the player teleports there.
  # Recommended for top-notch CPUs or very small amounts of players.
  loading-type: ULTRA-FAST
  
  # Radius of loading if FAST, NORMAL, SAFE or ULTRA-SAFE is
  # enabled. If larger than server view/render distance in
  # server.properties, then will override.
  loading-radius: 3
  
  # After rebooting or timers resetting, what delay should there
  # be until timers are initialized again?
  timer-load-delay: 10
  
  # How many ticks after teleporting/kicking players should
  # the world start to reset? At least 10 ticks is recommended.
  world-reset-delay: 15
  
  # Amount of seconds between teleportation of players back to the
  # world. The higher the number, the less stress on the server.
  # Highly recommended enabling if using random teleportation.
  recursive-teleporting:
    enabled: true
    milliseconds: 150
  
  # Sends a detailed, spaced out message during chunk loading.
  # NOTE: not supported on LEGACY versions.
  detailed-messages: true
  
  # Fixes glitch in legacy versions 1.8 and 1.9 where a player
  # suffocates in a block when teleported to the world.
  fix-suffocation-teleport-1_8-1_9: true
  
  # Fixes being teleported to an unsafe location in the over world
  # and end when rejoining the server to a reset world.
  fix-suffocation-on-join: true
  
  hooks:
    # If enabled, when a world is reset, all regions will be deleted.
    world-guard-delete: false
    
    # If enabled, will make sure warps are saved.
    save-cmi-warps: true
    
    # If enabled, will refresh CMI portals.
    refresh-cmi-portals: false
    
    # If enabled, will refresh Multiverse portals.
    refresh-mv-portals: true
  
  # updates the config every time you update. Prior strings will
  # remain the same! NOTE: disabling this will leave new settings
  # as default and new lang string won't send.
  auto-update-configs:
    config: true
    
    lang: true
  lang: en
# en = english (default), es = español, ru = русский.
`

This worlds.yml
`worlds:
  10Years:
    enabled: true
    last-saved: true
    settings:
      time:
        - '****-**-** **:** 24h' # 每24小时
      #  - '****-**-** **:00 2h' # 每2小时的xx:00
      #  - '****-**-** 14:30 3d' # every 3rd day at 2:30 pm
      #  - '****-**-20 09:00 2M' # every other month, on the 20th, at 9:00 am
       # - '****-08-20 13:45 12M' # every August 20, at 1:45 pm
       # - '2021-08-20 17:00' # august 20, 2021, 5:00 pm
      message: '{world}已经恢复初始'
      seed: DEFAULT
#注意：如果last-saved为“true”，则不起作用
#对随机种子使用“random”
#“默认”是指相同的种子
#自定义种子的示例：
#seed:2156120156/seed:'myppbig'>>用于纯文本
      environment: DEFAULT
        # NORMAL, THE_END, NETHER, DEFAULT
      generator: DEFAULT
#将其添加到bukkit.yml中并在此处添加之前重新启动。
#在此处设置生成器-通常是插件的名称。请
#站在他们这边审查WIKI。同一生成器的DEFAULT。
      safe-world:
        enabled: false #如果禁用，它将踢出所有玩家
        world: 'world'
        delay: 5 # 世界被重置为传送回来后的延迟
#-1如果不需要返回tp
        spawn: DEFAULT # 使用“15，52，-231”进行自定义生成
      warning:
        enabled: true
        message: '&c警告: 正在重置地图 {world}  {time}.'
        time: [1800, 600, 300, 60, 5] #重置发生前的秒
#30分钟、10分钟、5分钟、1分钟、5秒
        title:
          title: '警告'
          sub-title: '正在重置 {time}!'
          fade: [20, 60, 20] # 渐隐，停留，渐隐
      commands:
        - '[all-players] eco give {player} 500'
        # placeholders: {playerUUID} {playerName} {playerDisplayName} {world}
        - '[world-players] eco give {player} 25'
        - '[world-players:world_name] eco give {player} 25'
        - '[general] broadcast 正在重置世界：{world}!'

`

<img width="653" alt="image" src="https://github.com/Kihsomray/CyberWorldReset/assets/141799770/66056dd0-cd38-4a1a-ad97-a865bac77232">
<img width="263" alt="image" src="https://github.com/Kihsomray/CyberWorldReset/assets/141799770/79d86964-97ed-4526-86ec-41a1b94f35d8">
<img width="648" alt="image" src="https://github.com/Kihsomray/CyberWorldReset/assets/141799770/7957e7a5-5378-46b5-985a-1ec3ed410fd9">

**Comment by Kihsomray** [comment]
The name of your file "10Years.zip" does not follow the correct format (look at the one below it), so it will not be able to parse it in CyberWorldReset. Please use the correct format: `<world>_save_yyyy-MM-dd_hh-mm-ss.zip`.

**Comment by Leoparking** [comment]
> The name of your file "10Years.zip" does not follow the correct format (look at the one below it), so it will not be able to parse it in CyberWorldReset. Please use the correct format: `<world>_save_yyyy-MM-dd_hh-mm-ss.zip`.

What about the one down there?🤣↓

**Comment by Kihsomray** [comment]
That one is correct, it should parse it. But the first one is wrong.
